export const TechData = [
  'Aggregator Platform',
  'AI/Robotics',
  'Animated Comics/IP content creation',
  'AR/VR',
  'Big Data',
  'CRM/ERP',
  'Data Analytics/AI',
  'DevOps',
  'eCommerce',
  'Embedded/DSP',
  'Fintech',
  'Gaming',
  'IOT/Hardware/Wearable Technology',
  'Logistics',
  'Mobile Apps/Mobile Technology',
  'OEM/Electronics',
  'PR & Communication and Media',
  'Robotics',
  'SAAS Production/ Solution',
  'Sharing Economy',
  'Smart Cities',
  'Social Relevance',
  'Sustainable/ Renewable',
  'Telecommunications',
  'Visual Effects',
  'Web Platform',
  'Plant Biotech',
  'Plant Genomics',
  'Bio-Fertilizers',
  'Precision Farming',
  'Others',
];
export const industryData = [
  'Aerospace',
  'Agriculture',
  'Automotive(Fuel Based & EV)',
  'Animation,Visual Effects,Gaming & Comics (AVGC)',
  'Banking & Finance',
  'Biotechnology',
  'Clean-Tech',
  'Coal',
  'Construction & Furniture',
  'Consulting & Operations',
  'Consumer Electronics',
  'Ed-Tech',
  'Education',
  'Electronics, System Design & Manufacturing (ESDM)',
  'Fashion & Apparel',
  'Food & Beverages/ Food Processing',
  'Healthcare',
  'Human Resources',
  'Industrial Machinery & Manufacturing',
  'IT/ ITES',
  'Jewellery',
  'Kannada & Culture',
  'Legal/ Law',
  'Lifesciences',
  'Marketing',
  'Media & Advertising',
  'Med-Tech',
  'Metallurgy',
  'Mining',
  'Petroleum',
  'Pharma',
  'Railways',
  'Shipping',
  'Smart-City',
  'Telecommunications',
  'Textiles',
  'Tourism',
  'Transportation',
  'veterinary',
  'wellness',
];
export const districtData = [
  'Bagalkote',
  'Belagavi',
  'Bellary',
  'Bengaluru Rural',
  'Bengaluru Urban',
  'Bidar',
  'Chamarajanagar',
  'Chikkaballapur',
  'Chikmagalur',
  'Chitradurga',
  'Dakshina Kannada',
  'Davanagere',
  'Dharwad',
  'Gadag',
  'Hassan',
  'Haveri',
  'Kalburgi',
  'Kodagu',
  'Kolar',
  'Koppala',
  'Mandya',
  'Mysuru',
  'Raichur',
  'Ramanagara',
  'Shimoga',
  'Tumkur',
  'Udupi',
  'Uttara Kannada',
  'Vijayanagara',
  'Vijayapura',
  'Yadagiri',
];
